import type {
  ActivityEvent,
  Alert,
  DashboardSummary,
  HealthStatus,
  Machine,
  MachineStatusFilter,
  MaintenanceNotification,
} from "./types";

// Static timestamps from the synthetic demo snapshot; they never advance at runtime.
export const machines = [
  {
    id: "M-01",
    name: "Torno CNC principal",
    type: "Torno CNC",
    model: "Haas ST-30",
    visual: "lathe",
    status: "critical",
    statusLabel: "Riesgo crítico",
    criticality: "Alta",
    riskScore: 92,
    updatedAt: "2026-04-27T10:00:00-03:00",
    sector: "Línea A · Mecanizado pesado",
    summary: "El índice demo concentra la atención por una tendencia térmica y vibratoria sostenida.",
    signal: "Temperatura y vibración aumentaron durante las últimas lecturas simuladas.",
    recommendation: "Solicitar una inspección del especialista antes de programar cualquier intervención.",
    operating: true,
    sensors: [
      {
        key: "temperature",
        label: "Temperatura",
        value: 95.2,
        unit: "°C",
        change: 12.4,
        tone: "critical",
        points: [84.7, 87.1, null, 89.7, 92.6, 95.2],
      },
      {
        key: "vibration",
        label: "Vibración",
        value: 4.8,
        unit: "mm/s",
        change: 18.5,
        tone: "critical",
        points: [4.05, 4.12, 4.2, 4.36, 4.61, 4.8],
      },
      {
        key: "pressure",
        label: "Presión",
        value: 5.6,
        unit: "bar",
        change: 3.7,
        tone: "neutral",
        points: [5.4, 5.3, 5.5, 5.4, 5.5, 5.6],
      },
    ],
  },
  {
    id: "M-02",
    name: "Centro de mecanizado A2",
    type: "Centro de mecanizado",
    model: "DMG Mori CMX 1100 V",
    visual: "machining-center",
    status: "watch",
    statusLabel: "Bajo observación",
    criticality: "Alta",
    riskScore: 67,
    updatedAt: "2026-04-27T09:58:00-03:00",
    sector: "Línea A · Celdas CNC",
    summary: "La máquina continúa operativa, con una desviación moderada que requiere seguimiento.",
    signal: "La vibración se mantiene por encima de su referencia simulada desde hace seis horas.",
    recommendation: "Incluir el equipo en la próxima ronda y validar la señal antes de cambiar el plan.",
    operating: true,
    sensors: [
      {
        key: "temperature",
        label: "Temperatura",
        value: 80.1,
        unit: "°C",
        change: 5.3,
        tone: "warning",
        points: [76.1, 76.8, 77.5, 78.6, null, 80.1],
      },
      {
        key: "vibration",
        label: "Vibración",
        value: 3.8,
        unit: "mm/s",
        change: 11.8,
        tone: "warning",
        points: [3.4, 3.5, 3.48, 3.62, 3.75, 3.8],
      },
      {
        key: "current",
        label: "Corriente",
        value: 41.3,
        unit: "A",
        change: 2.2,
        tone: "neutral",
        points: [40.4, 40.8, 40.5, 41, 41.2, 41.3],
      },
    ],
  },
  {
    id: "M-03",
    name: "Compresor de tornillo",
    type: "Compresor",
    model: "Atlas Copco GA 37",
    visual: "compressor",
    status: "critical",
    statusLabel: "Riesgo crítico",
    criticality: "Alta",
    riskScore: 86,
    updatedAt: "2026-04-27T09:55:00-03:00",
    sector: "Servicios auxiliares · Aire comprimido",
    summary: "Una caída de presión simulada vuelve prioritario revisar el suministro de aire.",
    signal: "La presión descendió mientras la temperatura de descarga continuó en ascenso.",
    recommendation: "Pedir validación técnica en campo y confirmar redundancia antes de intervenir.",
    operating: true,
    sensors: [
      {
        key: "temperature",
        label: "Temperatura",
        value: 91.7,
        unit: "°C",
        change: 10.1,
        tone: "critical",
        points: [83.3, 84.8, 86.2, 88.4, 90.3, 91.7],
      },
      {
        key: "vibration",
        label: "Vibración",
        value: 3.6,
        unit: "mm/s",
        change: 5.9,
        tone: "warning",
        points: [3.4, 3.35, 3.48, null, 3.55, 3.6],
      },
      {
        key: "pressure",
        label: "Presión",
        value: 3.1,
        unit: "bar",
        change: -22.5,
        tone: "critical",
        points: [4, 3.9, 3.75, 3.5, 3.28, 3.1],
      },
    ],
  },
  {
    id: "M-04",
    name: "Fresadora CNC B1",
    type: "Fresadora",
    model: "Bridgeport V1000",
    visual: "mill",
    status: "healthy",
    statusLabel: "Normal",
    criticality: "Media",
    riskScore: 23,
    updatedAt: "2026-04-27T09:53:00-03:00",
    sector: "Línea B · Mecanizado de precisión",
    summary: "Las señales simuladas permanecen estables dentro de su referencia operativa.",
    signal: "Sin cambios relevantes en temperatura, vibración o carga.",
    recommendation: "Mantener el monitoreo habitual; no se sugiere una intervención.",
    operating: true,
    sensors: [
      {
        key: "temperature",
        label: "Temperatura",
        value: 68.4,
        unit: "°C",
        change: 1.2,
        tone: "neutral",
        points: [67.6, 67.8, 68, 67.9, 68.2, 68.4],
      },
      {
        key: "vibration",
        label: "Vibración",
        value: 2.2,
        unit: "mm/s",
        change: 0,
        tone: "neutral",
        points: [2.2, 2.18, 2.21, 2.19, 2.2, 2.2],
      },
      {
        key: "current",
        label: "Corriente",
        value: 32.8,
        unit: "A",
        change: -0.9,
        tone: "neutral",
        points: [33.1, 33, 32.9, 33, 32.8, 32.8],
      },
    ],
  },
  {
    id: "M-05",
    name: "Central hidráulica A1",
    type: "Sistema hidráulico",
    model: "Bosch Rexroth CytroPac",
    visual: "hydraulic",
    status: "watch",
    statusLabel: "Bajo observación",
    criticality: "Alta",
    riskScore: 61,
    updatedAt: "2026-04-27T09:49:00-03:00",
    sector: "Línea A · Potencia hidráulica",
    summary: "La presión simulada oscila más de lo habitual, sin evidencia suficiente para detener el equipo.",
    signal: "Se observaron oscilaciones de presión y una lectura ausente en la ventana reciente.",
    recommendation: "Revisar nivel y posibles fugas durante la próxima inspección humana.",
    operating: true,
    sensors: [
      {
        key: "temperature",
        label: "Temperatura",
        value: 71.6,
        unit: "°C",
        change: 3.5,
        tone: "neutral",
        points: [69.2, 69.8, 70.4, 70.9, 71.2, 71.6],
      },
      {
        key: "vibration",
        label: "Vibración",
        value: 2.9,
        unit: "mm/s",
        change: 7.4,
        tone: "warning",
        points: [2.7, 2.75, 2.68, 2.82, 2.88, 2.9],
      },
      {
        key: "pressure",
        label: "Presión",
        value: 4.2,
        unit: "bar",
        change: -12.5,
        tone: "warning",
        points: [4.8, 4.45, null, 4.72, 4.1, 4.2],
      },
    ],
  },
  {
    id: "M-06",
    name: "Extractor auxiliar",
    type: "Equipo auxiliar",
    model: "Ziehl-Abegg ZAplus",
    visual: "auxiliary",
    status: "maintenance",
    statusLabel: "En mantenimiento",
    criticality: "Baja",
    riskScore: 35,
    updatedAt: "2026-04-27T09:45:00-03:00",
    sector: "Servicios auxiliares · Ventilación",
    summary: "El equipo figura detenido por una intervención planificada en esta simulación.",
    signal: "No hay lecturas operativas mientras se realiza el mantenimiento.",
    recommendation: "Mantenerlo fuera de servicio hasta que el responsable valide el cierre del trabajo.",
    operating: false,
    sensors: [
      {
        key: "temperature",
        label: "Temperatura",
        value: 29.1,
        unit: "°C",
        change: -48.7,
        tone: "neutral",
        points: [56.7, 48.2, 39.5, 32.8, 29.1, null],
      },
      {
        key: "vibration",
        label: "Vibración",
        value: 0,
        unit: "mm/s",
        change: -100,
        tone: "neutral",
        points: [2.1, 1.4, 0.6, 0, 0, null],
      },
      {
        key: "current",
        label: "Corriente",
        value: 0,
        unit: "A",
        change: -100,
        tone: "neutral",
        points: [18.4, 11.2, 4.7, 0, 0, null],
      },
    ],
  },
  {
    id: "M-07",
    name: "Torno paralelo B2",
    type: "Torno convencional",
    model: "Romi Tormax 30A",
    visual: "lathe",
    status: "healthy",
    statusLabel: "Normal",
    criticality: "Media",
    riskScore: 16,
    updatedAt: "2026-04-27T09:42:00-03:00",
    sector: "Línea B · Preparación",
    summary: "El comportamiento simulado se mantiene estable durante el turno.",
    signal: "No se detectaron desvíos relevantes en las señales disponibles.",
    recommendation: "Continuar con la rutina de inspección vigente.",
    operating: true,
    sensors: [
      {
        key: "temperature",
        label: "Temperatura",
        value: 62.7,
        unit: "°C",
        change: 0.8,
        tone: "neutral",
        points: [62.2, 62.4, 62.1, 62.5, 62.6, 62.7],
      },
      {
        key: "vibration",
        label: "Vibración",
        value: 1.9,
        unit: "mm/s",
        change: -1,
        tone: "neutral",
        points: [1.92, 1.95, 1.9, 1.88, 1.91, 1.9],
      },
      {
        key: "current",
        label: "Corriente",
        value: 24.3,
        unit: "A",
        change: 0.4,
        tone: "neutral",
        points: [24.2, 24.1, 24.3, 24.2, 24.4, 24.3],
      },
    ],
  },
  {
    id: "M-08",
    name: "Centro de mecanizado B3",
    type: "Centro de mecanizado",
    model: "Mazak VCN-530C",
    visual: "machining-center",
    status: "healthy",
    statusLabel: "Normal",
    criticality: "Baja",
    riskScore: 11,
    updatedAt: "2026-04-27T09:40:00-03:00",
    sector: "Línea B · Acabado",
    summary: "Las lecturas simuladas muestran una condición estable y baja prioridad relativa.",
    signal: "Temperatura, vibración y corriente permanecen sin cambios significativos.",
    recommendation: "Mantener el monitoreo habitual y revisar según el calendario vigente.",
    operating: true,
    sensors: [
      {
        key: "temperature",
        label: "Temperatura",
        value: 59.8,
        unit: "°C",
        change: -0.3,
        tone: "neutral",
        points: [60, 59.9, 60.1, 59.8, 59.9, 59.8],
      },
      {
        key: "vibration",
        label: "Vibración",
        value: 1.7,
        unit: "mm/s",
        change: 0,
        tone: "neutral",
        points: [1.7, 1.69, 1.71, 1.7, 1.68, 1.7],
      },
      {
        key: "current",
        label: "Corriente",
        value: 28.6,
        unit: "A",
        change: 1.1,
        tone: "neutral",
        points: [28.3, 28.4, 28.2, 28.5, 28.5, 28.6],
      },
    ],
  },
] satisfies readonly Machine[];

export const alerts: readonly Alert[] = [
  {
    id: "ALT-001",
    machineId: "M-01",
    title: "Tendencia térmica prioritaria",
    description: "Alerta simulada pendiente de revisión humana por temperatura y vibración en ascenso.",
    severity: "critical",
    timestamp: "2026-04-27T09:51:00-03:00",
    status: "open",
    category: "condition",
  },
  {
    id: "ALT-002",
    machineId: "M-03",
    title: "Caída sostenida de presión",
    description: "Un responsable está evaluando la señal simulada antes de autorizar una acción.",
    severity: "critical",
    timestamp: "2026-04-27T09:35:00-03:00",
    status: "under-review",
    category: "sensor",
  },
  {
    id: "ALT-003",
    machineId: "M-02",
    title: "Vibración fuera de referencia",
    description: "La revisión de turno fue planificada por una persona; no existe acción automática.",
    severity: "high",
    timestamp: "2026-04-27T08:40:00-03:00",
    status: "planned",
    category: "condition",
  },
  {
    id: "ALT-004",
    machineId: "M-05",
    title: "Oscilación del circuito hidráulico",
    description: "Registro simulado abierto para que mantenimiento confirme nivel, presión y posibles fugas.",
    severity: "medium",
    timestamp: "2026-04-27T07:25:00-03:00",
    status: "open",
    category: "maintenance",
  },
] satisfies readonly Alert[];

export const notifications = [
  {
    id: "NOT-001",
    machineId: "M-01",
    type: "new-alert",
    title: "Nueva alerta simulada en M-01",
    message: "La tendencia térmica requiere revisión humana prioritaria.",
    read: false,
    timestamp: "2026-04-27T09:52:00-03:00",
  },
  {
    id: "NOT-002",
    machineId: "M-03",
    type: "status-change",
    title: "M-03 pasó a riesgo crítico",
    message: "Cambio de estado simulado; un responsable debe validar el diagnóstico.",
    read: false,
    timestamp: "2026-04-27T09:36:00-03:00",
  },
  {
    id: "NOT-003",
    machineId: "M-02",
    type: "recommendation",
    title: "Inspección sugerida para M-02",
    message: "La recomendación demo propone revisar vibración en la próxima ronda.",
    read: false,
    timestamp: "2026-04-27T08:42:00-03:00",
  },
  {
    id: "NOT-004",
    machineId: "M-06",
    type: "maintenance",
    title: "Mantenimiento simulado en curso",
    message: "M-06 permanece detenido hasta la validación de cierre del responsable.",
    read: true,
    timestamp: "2026-04-27T08:05:00-03:00",
  },
  {
    id: "NOT-005",
    machineId: "M-05",
    type: "status-change",
    title: "M-05 quedó bajo observación",
    message: "El cambio demo refleja oscilaciones de presión aún no confirmadas en campo.",
    read: true,
    timestamp: "2026-04-27T07:27:00-03:00",
  },
] satisfies readonly MaintenanceNotification[];

export const activityEvents = [
  {
    id: "EVT-001",
    machineId: "M-01",
    type: "alert",
    title: "Alerta de condición creada",
    detail: "Evento simulado: la señal quedó abierta para revisión humana.",
    timestamp: "2026-04-27T09:51:00-03:00",
  },
  {
    id: "EVT-002",
    machineId: "M-03",
    type: "status-change",
    title: "Estado actualizado a riesgo crítico",
    detail: "Cambio simulado generado por la caída de presión del compresor.",
    timestamp: "2026-04-27T09:35:00-03:00",
  },
  {
    id: "EVT-003",
    machineId: "M-02",
    type: "inspection",
    title: "Inspección agregada a la ronda",
    detail: "Un responsable incluyó manualmente la revisión de vibración.",
    timestamp: "2026-04-27T08:45:00-03:00",
  },
  {
    id: "EVT-004",
    machineId: "M-06",
    type: "maintenance",
    title: "Mantenimiento planificado iniciado",
    detail: "Registro demo: el equipo quedó fuera de operación durante la intervención.",
    timestamp: "2026-04-27T08:00:00-03:00",
  },
  {
    id: "EVT-005",
    machineId: "M-05",
    type: "status-change",
    title: "Equipo puesto bajo observación",
    detail: "El cambio simulado espera confirmación durante la próxima ronda de campo.",
    timestamp: "2026-04-27T07:25:00-03:00",
  },
] satisfies readonly ActivityEvent[];

const counts = machines.reduce<Record<HealthStatus, number>>(
  (result, machine) => ({ ...result, [machine.status]: result[machine.status] + 1 }),
  { healthy: 0, watch: 0, critical: 0, maintenance: 0 },
);

export const dashboardSummary = {
  total: machines.length,
  counts,
  highCriticality: machines.filter((machine) => machine.criticality === "Alta").length,
  activeAlerts: alerts.filter((alert) => alert.status !== "closed").length,
} satisfies DashboardSummary;

export const priorityMachines = [...machines].sort((left, right) => right.riskScore - left.riskScore);

export function filterMachinesByStatus(
  items: readonly Machine[],
  status: MachineStatusFilter,
): readonly Machine[] {
  return status === "all" ? items : items.filter((machine) => machine.status === status);
}

export function markNotificationsRead(
  items: readonly MaintenanceNotification[],
  id?: string,
): MaintenanceNotification[] {
  return items.map((notification) =>
    id === undefined || notification.id === id ? { ...notification, read: true } : notification,
  );
}
