import Link from "next/link";
import { getAudit } from "@/modules/admin/service";
import { Empty, Field, formatDate, PageTitle, scopeLabels } from "../_components";

export default async function AuditPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { logs, filters, actions } = await getAudit(await searchParams);
  return <>
    <PageTitle title="Auditoría" description="Registro de cambios administrativos visible dentro de tu ámbito. Las contraseñas, sesiones y enlaces privados no se almacenan en este registro." />
    <form className="admin-panel mb-5 grid items-end gap-4 sm:grid-cols-2 lg:grid-cols-[1fr_260px_auto_auto]" method="get"><Field label="Actor, entidad o referencia"><input className="admin-input" defaultValue={filters.q} maxLength={120} name="q" placeholder="Identificador o tipo de entidad" type="search" /></Field><Field label="Acción"><select className="admin-input" defaultValue={filters.action} name="action"><option value="">Todas</option>{actions.map((action) => <option key={action} value={action}>{action}</option>)}</select></Field><button className="admin-button" type="submit">Filtrar</button><Link className="inline-flex min-h-11 items-center text-sm text-action" href="/admin/audit">Limpiar</Link></form>
    <section className="admin-panel" aria-label="Registro de auditoría"><p className="mb-4 text-sm text-secondary">{logs.length} eventos visibles · Más recientes primero</p>{logs.length ? <ol className="divide-y divide-default">{logs.map((log) => <li className="py-5 first:pt-0" key={log.id}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h2 className="text-sm font-semibold">{log.action}</h2><p className="mt-1 text-xs text-secondary">{log.entityType} · {scopeLabels[log.scopeType]}{log.scopeRef ? ` · ${log.scopeRef}` : ""}</p></div><time className="font-mono text-xs text-secondary" dateTime={log.createdAt.toISOString()}>{formatDate(log.createdAt)} UTC</time></div><dl className="mt-3 grid gap-3 text-xs sm:grid-cols-2"><div><dt className="text-muted">Actor</dt><dd className="mt-1 break-all font-mono">{log.actorUserId ?? "Sistema / sin sesión"}</dd></div><div><dt className="text-muted">Entidad</dt><dd className="mt-1 break-all font-mono">{log.entityId ?? "—"}</dd></div></dl>{log.beforeData !== null || log.afterData !== null ? <details className="mt-3"><summary className="flex min-h-11 cursor-pointer items-center text-xs font-medium text-action">Ver cambios registrados</summary><div className="grid gap-3 lg:grid-cols-2"><div><h3 className="mb-2 text-xs font-semibold">Antes</h3><pre className="max-h-80 overflow-auto rounded border border-default bg-subtle p-3 text-[11px] leading-5">{JSON.stringify(log.beforeData, null, 2)}</pre></div><div><h3 className="mb-2 text-xs font-semibold">Después</h3><pre className="max-h-80 overflow-auto rounded border border-default bg-subtle p-3 text-[11px] leading-5">{JSON.stringify(log.afterData, null, 2)}</pre></div></div></details> : null}</li>)}</ol> : <Empty />}</section>
  </>;
}
