import Link from "next/link";
import { AdminForm } from "@/app/_components/admin-form";
import { getRoles } from "@/modules/admin/service";
import { Empty, Field, PageTitle, PermissionFields, permissionLabels } from "../_components";
import { saveRoleAction } from "../actions";

export default async function RolesPage() {
  const { roles, permissions, canCreate, canSetPermissions, grantablePermissions } = await getRoles();
  return <>
    <PageTitle title="Roles y permisos" description="Un rol reúne permisos; las asignaciones determinan dónde y durante cuánto tiempo se aplican. El sistema verifica permisos efectivos, no nombres de roles." />
    <section className="admin-panel"><h2 className="mb-4 text-lg font-semibold">Roles disponibles</h2>{roles.length ? <div className="overflow-x-auto"><table className="admin-table"><thead><tr><th scope="col">Rol</th><th scope="col">Tipo</th><th scope="col">Permisos</th><th scope="col">Asignaciones</th><th scope="col">Acción</th></tr></thead><tbody>{roles.map((role) => <tr key={role.id}><td><p className="font-medium">{role.name}</p>{role.description ? <p className="mt-1 max-w-lg text-xs text-slate-600">{role.description}</p> : null}</td><td className="text-xs">{role.isSystem ? "Sistema" : "Personalizado"}</td><td className="font-mono tabular-nums">{role.permissions.length}</td><td className="font-mono tabular-nums">{role._count.assignments}</td><td><Link aria-label={`Ver rol ${role.name}`} className="inline-flex min-h-11 items-center font-medium text-teal-700" href={`/admin/roles/${role.id}`}>Ver detalle →</Link></td></tr>)}</tbody></table></div> : <Empty />}</section>
    <section className="admin-panel mt-6"><h2 className="text-lg font-semibold">Matriz de permisos</h2><p className="mb-4 mt-2 text-sm text-slate-600">El ámbito y la vigencia de cada asignación limitan estos permisos.</p><div className="overflow-x-auto"><table className="admin-table"><caption className="sr-only">Permisos incluidos en cada rol</caption><thead><tr><th scope="col">Permiso</th>{roles.map((role) => <th className="text-center" key={role.id} scope="col">{role.name}</th>)}</tr></thead><tbody>{permissions.map((permission) => <tr key={permission}><th className="font-normal" scope="row"><span className="block text-slate-900">{permissionLabels[permission]}</span><span className="font-mono text-[11px] text-slate-500">{permission}</span></th>{roles.map((role) => <td className="text-center" key={role.id}>{role.permissions.some((item) => item.permission.key === permission) ? <span className="font-medium text-emerald-700">Sí</span> : <span className="text-slate-500">—<span className="sr-only">Sin permiso</span></span>}</td>)}</tr>)}</tbody></table></div></section>
    {canCreate ? <section className="admin-panel mt-6 max-w-4xl"><h2 className="mb-4 text-lg font-semibold">Crear rol personalizado</h2><AdminForm action={saveRoleAction} confirmLabel="Confirmo la creación del rol y sus permisos." submitLabel="Crear rol"><input name="roleId" type="hidden" value="" /><input name="mode" type="hidden" value="create" /><Field label="Nombre del rol"><input className="admin-input" maxLength={64} minLength={3} name="name" required /></Field><Field label="Descripción (opcional)"><textarea className="admin-input" maxLength={300} name="description" rows={2} /></Field>{canSetPermissions ? <PermissionFields permissions={grantablePermissions} /> : <p className="text-sm leading-6 text-slate-600">Podés crear el rol vacío. La asignación de permisos requiere el permiso «Administrar permisos de roles».</p>}</AdminForm></section> : null}
  </>;
}
