import Link from "next/link";
import { getAdminOverview } from "@/modules/admin/service";
import { Empty, formatDate, PageTitle } from "./_components";

export default async function AdminPage() {
  const summary = await getAdminOverview();
  const counters = [["Usuarios activos", summary.activeUsers], ["Invitados", summary.invitedUsers], ["Suspendidos", summary.suspendedUsers], ["Roles", summary.roleCount], ["Asignaciones activas", summary.activeAssignments], ["Vencen en 7 días", summary.expiringAssignments]] as const;
  return <><PageTitle title="Administración" description="Personas, permisos y vigencias dentro de tu ámbito de administración. Los indicadores solo incluyen los datos que podés consultar." /><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{counters.filter(([, count]) => count !== null).map(([label, count]) => <div className="admin-panel" key={label}><dt className="text-sm text-slate-600">{label}</dt><dd className="mt-3 font-mono text-3xl tabular-nums text-slate-900">{count}</dd></div>)}</dl>{summary.latestActions !== null ? <section className="admin-panel mt-6"><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-semibold">Últimas acciones administrativas</h2><Link className="inline-flex min-h-11 items-center text-sm text-teal-700" href="/admin/audit">Ver auditoría</Link></div>{summary.latestActions.length ? <ol className="divide-y divide-slate-200">{summary.latestActions.map((entry) => <li className="flex flex-wrap items-center justify-between gap-3 py-4" key={entry.id}><div><p className="text-sm font-medium">{entry.action}</p><p className="mt-1 text-xs text-slate-600">{entry.entityType} · {entry.scopeRef ?? "Global"}</p></div><time className="font-mono text-xs text-slate-600" dateTime={entry.createdAt.toISOString()}>{formatDate(entry.createdAt)}</time></li>)}</ol> : <Empty />}</section> : <p className="mt-6 text-sm text-slate-600">Elegí una sección disponible en el menú para administrar tu ámbito.</p>}</>;
}
