import Link from "next/link";
import { AdminForm } from "@/app/_components/admin-form";
import { getAccess } from "@/modules/admin/service";
import { Empty, Field, formatDate, PageTitle, scopeLabels, Status } from "../_components";
import { saveResourceAction } from "../actions";

type Resource = Awaited<ReturnType<typeof getAccess>>["resources"][number];

function ResourceFields({ resources, resource }: { resources: Resource[]; resource?: Resource }) {
  return <><input name="resourceId" type="hidden" value={resource?.id ?? ""} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Tipo de recurso"><select className="admin-input" defaultValue={resource?.scopeType ?? "ORGANIZATION"} name="scopeType" required><option value="ORGANIZATION">Organización</option><option value="PLANT">Planta</option><option value="AREA">Área</option><option value="MACHINE">Máquina</option></select></Field><Field label="Referencia estable"><input className="admin-input font-mono" defaultValue={resource?.scopeRef ?? ""} maxLength={100} name="scopeRef" pattern="[A-Za-z0-9._:\-]+" required /></Field><Field label="Nombre visible"><input className="admin-input" defaultValue={resource?.name ?? ""} maxLength={120} minLength={2} name="name" required /></Field><Field label="Recurso padre"><select className="admin-input" defaultValue={resource?.parentId ?? ""} name="parentId"><option value="">Sin padre</option>{resources.filter((item) => item.id !== resource?.id && item.scopeType !== "MACHINE").map((item) => <option key={item.id} value={item.id}>{scopeLabels[item.scopeType]} · {item.name} ({item.scopeRef})</option>)}</select></Field></div></>;
}

export default async function AccessPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { assignments, users, roles, filters, machineResources, resources, canEditResources } = await getAccess(await searchParams);
  return <>
    <PageTitle title="Accesos y vigencias" description="Cada asignación combina una persona, un rol, un ámbito y un período. La suspensión de una cuenta bloquea todas sus asignaciones." />
    <form className="admin-panel mb-5" method="get"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Usuario"><select className="admin-input" defaultValue={filters.userId} name="userId"><option value="">Todos los visibles</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select></Field><Field label="Rol"><select className="admin-input" defaultValue={filters.roleId} name="roleId"><option value="">Todos</option>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></Field><Field label="Tipo de ámbito"><select className="admin-input" defaultValue={filters.scopeType} name="scopeType"><option value="">Todos</option>{Object.entries(scopeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Acceso efectivo a máquina"><select className="admin-input" defaultValue={filters.machineRef} name="machineRef"><option value="">Todas</option>{machineResources.map((resource) => <option key={resource.id} value={resource.scopeRef}>{resource.name} ({resource.scopeRef})</option>)}</select></Field><Field label="Estado"><select className="admin-input" defaultValue={filters.state} name="state"><option value="">Todos</option>{["Activo", "Pendiente", "Vencido", "Suspendido"].map((state) => <option key={state} value={state}>{state}</option>)}</select></Field><Field label="Vigencia"><select className="admin-input" defaultValue={filters.validity} name="validity"><option value="">Cualquier período</option><option value="current">Vigentes ahora</option><option value="expiring">Vencen en 7 días</option><option value="future">Comienzan en el futuro</option><option value="expired">Período vencido</option></select></Field></div><div className="mt-4 flex items-center gap-5"><button className="admin-button" type="submit">Filtrar accesos</button><Link className="inline-flex min-h-11 items-center text-sm text-teal-700" href="/admin/access">Limpiar</Link></div></form>
    <section className="admin-panel"><h2 className="mb-4 text-lg font-semibold">Asignaciones <span className="font-mono text-sm font-normal text-slate-500">({assignments.length})</span></h2>{assignments.length ? <div className="overflow-x-auto"><table className="admin-table"><thead><tr><th scope="col">Usuario</th><th scope="col">Rol</th><th scope="col">Ámbito</th><th scope="col">Período (UTC)</th><th scope="col">Estado</th><th scope="col">Detalle</th></tr></thead><tbody>{assignments.map((assignment) => <tr key={assignment.id}><td><p className="font-medium">{assignment.user.name}</p><p className="mt-1 text-xs text-slate-600">{assignment.user.email}</p></td><td className="text-xs">{assignment.role.name}</td><td><p className="text-xs">{scopeLabels[assignment.scopeType]} · {assignment.resourceName}</p><p className="mt-1 font-mono text-[11px] text-slate-500">{assignment.scopeRef ?? "GLOBAL"}</p></td><td className="text-xs"><p>{assignment.validFrom ? formatDate(assignment.validFrom) : "Sin inicio"}</p><p className="mt-1 text-slate-600">{assignment.validUntil ? formatDate(assignment.validUntil) : "Sin vencimiento"}</p></td><td><Status value={assignment.state} /></td><td><Link aria-label={`Ver accesos de ${assignment.user.name}`} className="inline-flex min-h-11 items-center text-sm font-medium text-teal-700" href={`/admin/users/${assignment.user.id}#access`}>Ver accesos →</Link></td></tr>)}</tbody></table></div> : <Empty />}</section>
    {users.length ? <section className="admin-panel mt-6"><h2 className="text-lg font-semibold">Accesos por usuario</h2><p className="mb-4 mt-2 text-sm text-slate-600">Abrí una persona para agregar, editar o revocar asignaciones según tus permisos. También se incluyen cuentas sin asignaciones.</p><ul className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{users.map((user) => <li key={user.id}><Link className="flex min-h-14 items-center justify-between gap-3 rounded border border-slate-200 px-3 py-2 text-sm hover:border-teal-700/40 hover:bg-teal-50" href={`/admin/users/${user.id}#access`}><span><span className="block font-medium">{user.name}</span><span className="text-xs text-slate-600">{user.assignments.length} asignaciones</span></span><span aria-hidden="true" className="text-teal-700">→</span></Link></li>)}</ul></section> : null}
    {resources.length || canEditResources ? <section className="admin-panel mt-6"><h2 className="text-lg font-semibold">Jerarquía de autorización</h2><p className="mb-4 mt-2 max-w-3xl text-sm leading-6 text-slate-600">Organización → planta → área → máquina. Una máquina puede estar sin padre hasta que se defina su ubicación. Esta jerarquía establece permisos; no modifica sensores, históricos ni datos técnicos.</p>{resources.length ? <ul className="divide-y divide-slate-200">{resources.map((resource) => <li className="py-4" key={resource.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">{resource.name}</p><p className="mt-1 text-xs text-slate-600">{scopeLabels[resource.scopeType]} · <span className="font-mono">{resource.scopeRef}</span> · Padre: {resources.find((item) => item.id === resource.parentId)?.name ?? "sin padre"}</p></div></div>{canEditResources ? <details className="mt-3"><summary className="flex min-h-11 cursor-pointer items-center text-sm font-medium text-teal-700">Editar recurso {resource.name}</summary><AdminForm action={saveResourceAction} className="max-w-3xl space-y-4 border-l-2 border-slate-200 pl-4" confirmLabel="Confirmo el cambio de jerarquía y su efecto sobre los accesos heredados." submitLabel="Guardar recurso"><ResourceFields resource={resource} resources={resources} /></AdminForm></details> : null}</li>)}</ul> : <Empty>No se definieron recursos de autorización.</Empty>}
      {canEditResources ? <div className="mt-5 max-w-3xl border-t border-slate-200 pt-5"><h3 className="mb-3 text-base font-semibold">Agregar recurso de autorización</h3><p className="mb-4 text-sm leading-6 text-slate-600">El padre debe tener un nivel superior. Para una máquina, usá su identificador del inventario. Un recurso con asignaciones no puede cambiar de tipo ni de referencia.</p><AdminForm action={saveResourceAction} confirmLabel="Confirmo la creación del recurso y su ubicación en la jerarquía." submitLabel="Crear recurso"><ResourceFields resources={resources} /></AdminForm></div> : null}
    </section> : null}
  </>;
}
